# Generated by Django 4.2.3 on 2023-08-12 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleModule', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 12), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
