# Generated by Django 4.2.3 on 2023-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleModule', '0005_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان نظر'),
        ),
    ]
