# Generated by Django 4.2.3 on 2023-08-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleModule', '0006_alter_articlecomment_options_articlecomment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='title',
        ),
    ]
