# Generated by Django 4.2.1 on 2023-07-18 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='productInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='حجم')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.productcategory', verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='فعال بودن/نبودن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(max_length=300, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='نام بازی'),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.productinformation', verbose_name='اطلاعات تکمیلی'),
        ),
    ]
