# Generated by Django 4.2.1 on 2023-07-18 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_producttags_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='حذف شده / نشده'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='حذف شده / نشده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
