# Generated by Django 4.2.3 on 2023-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='urlTitle',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
