# Generated by Django 4.2.3 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_productcategory_urltitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='urlTitle',
            field=models.CharField(db_index=True, default='url_title', max_length=300, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
