# Generated by Django 4.2.3 on 2023-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountModule', '0002_user_confirmpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmPass',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تصویر اواتار'),
        ),
    ]
