# Generated by Django 4.2.3 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountModule', '0003_remove_user_confirmpass_remove_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutUser',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شخص'),
        ),
    ]
