# Generated by Django 4.2.3 on 2023-08-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerLinksBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک در فوتر',
                'verbose_name_plural': 'دسته بندی های لینک در فوتر',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن'),
        ),
        migrations.CreateModel(
            name='footerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footerLinkBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteModule.footerlinksbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک در فوتر',
                'verbose_name_plural': 'لینک ها در فوتر',
            },
        ),
    ]
