# Generated by Django 4.2.3 on 2023-08-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteModule', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
