# Generated by Django 4.2.3 on 2023-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteModule', '0004_slider_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
