# Generated by Django 4.2.1 on 2023-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('fullName', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('message', models.TextField(max_length=300, verbose_name='متن تماس با ما')),
                ('isReadByAmin', models.BooleanField(verbose_name='خوانده شده توسط ادمین')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریح ایجاد')),
                ('response', models.TextField(verbose_name='متن پاسخ')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
