# Generated by Django 4.2.1 on 2023-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUsModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(verbose_name='متن پاسخ تماس با ما'),
        ),
    ]
