# Generated by Django 4.2.1 on 2023-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUsModule', '0002_alter_contactus_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='isReadByAmin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ تماس با ما'),
        ),
    ]
